apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: st01kcluster
spec:
  kafka:
    replicas: 3 
    version: 3.2.1
    listeners: 
      - name: plain
        port: 9092 
        type: internal 
        tls: false 
        configuration:
          useServiceDnsDomain: true 
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication: 
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication: 
          type: tls    
    authorization: 
      type: simple
    config: 
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      #log.message.format.version: "3.0"
    storage: 
      type: ephemeral
    # ...
  zookeeper: 
    replicas: 3 
    storage:
      type: ephemeral
      # ...
  entityOperator: 
    topicOperator: {}
    userOperator: {}